import { getDb } from "../db";

const TABLE_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS reimbursement_clients (id INTEGER PRIMARY KEY AUTOINCREMENT, legal_name TEXT NOT NULL, cnpj TEXT NOT NULL, state TEXT NOT NULL, client_type TEXT NOT NULL DEFAULT '', n2 INTEGER NOT NULL DEFAULT 0, n3 INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', created_by_email TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS reimbursement_clients_cnpj_state_idx ON reimbursement_clients(cnpj, state)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_clients_state_idx ON reimbursement_clients(state)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_clients_status_idx ON reimbursement_clients(status)`,
  "CREATE TABLE IF NOT EXISTS reimbursement_settings (setting_key TEXT PRIMARY KEY, numeric_value INTEGER NOT NULL, updated_by_email TEXT NOT NULL DEFAULT 'system', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)",
  `CREATE TABLE IF NOT EXISTS reimbursement_imports (id INTEGER PRIMARY KEY AUTOINCREMENT, file_name TEXT NOT NULL, storage_key TEXT NOT NULL DEFAULT '', content_type TEXT NOT NULL DEFAULT '', dealership_id INTEGER REFERENCES dealerships(id) ON DELETE SET NULL, price_list_import_id INTEGER REFERENCES price_list_imports(id) ON DELETE SET NULL, row_count INTEGER NOT NULL DEFAULT 0, total_quantity INTEGER NOT NULL DEFAULT 0, total_sales_cents INTEGER NOT NULL DEFAULT 0, total_cost_cents INTEGER NOT NULL DEFAULT 0, total_reimbursement_n2_cents INTEGER NOT NULL DEFAULT 0, total_reimbursement_n3_cents INTEGER NOT NULL DEFAULT 0, total_negotiation_cents INTEGER NOT NULL DEFAULT 0, tolerance_cents INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'processed', uploaded_by_email TEXT NOT NULL, uploaded_by_name TEXT NOT NULL DEFAULT '', decision_note TEXT NOT NULL DEFAULT '', decided_by_email TEXT NOT NULL DEFAULT '', decided_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_imports_dealership_idx ON reimbursement_imports(dealership_id)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_imports_status_idx ON reimbursement_imports(status)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_imports_created_at_idx ON reimbursement_imports(created_at)`,
  `CREATE TABLE IF NOT EXISTS reimbursement_sales (id INTEGER PRIMARY KEY AUTOINCREMENT, import_id INTEGER NOT NULL REFERENCES reimbursement_imports(id) ON DELETE CASCADE, dealership_id INTEGER REFERENCES dealerships(id) ON DELETE SET NULL, client_id INTEGER REFERENCES reimbursement_clients(id) ON DELETE SET NULL, price_list_import_id INTEGER REFERENCES price_list_imports(id) ON DELETE SET NULL, part_number TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', quantity INTEGER NOT NULL DEFAULT 0, cost_avg_unit_cents INTEGER NOT NULL DEFAULT 0, sale_net_unit_cents INTEGER NOT NULL DEFAULT 0, invoice_unit_cents INTEGER NOT NULL DEFAULT 0, client_name TEXT NOT NULL DEFAULT '', client_cnpj TEXT NOT NULL DEFAULT '', invoice_number TEXT NOT NULL DEFAULT '', state TEXT NOT NULL DEFAULT '', dealership_name TEXT NOT NULL DEFAULT '', margin_bps INTEGER NOT NULL DEFAULT 0, cost_total_cents INTEGER NOT NULL DEFAULT 0, liquid_total_cents INTEGER NOT NULL DEFAULT 0, net_price_used_cents INTEGER, calculation_base_cents INTEGER NOT NULL DEFAULT 0, reimbursement_cents INTEGER NOT NULL DEFAULT 0, reimbursement_program TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'N2 Não Elegível', negotiation_cents INTEGER NOT NULL DEFAULT 0, expected_n3_cents INTEGER, price_difference_cents INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_sales_import_idx ON reimbursement_sales(import_id)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_sales_dealership_idx ON reimbursement_sales(dealership_id)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_sales_pn_idx ON reimbursement_sales(part_number)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_sales_status_idx ON reimbursement_sales(status)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_sales_invoice_idx ON reimbursement_sales(invoice_number)`,
  `CREATE TABLE IF NOT EXISTS reimbursement_approvals (id INTEGER PRIMARY KEY AUTOINCREMENT, import_id INTEGER NOT NULL REFERENCES reimbursement_imports(id) ON DELETE CASCADE, action TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', actor_email TEXT NOT NULL, actor_name TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_approvals_import_idx ON reimbursement_approvals(import_id)`,
  `CREATE INDEX IF NOT EXISTS reimbursement_approvals_created_at_idx ON reimbursement_approvals(created_at)`,
] as const;

export async function ensureReimbursementStorage() {
  const { env } = await import("cloudflare:workers");
  if (!env.DB) throw new Error("Cloudflare D1 binding `DB` indisponível.");
  await env.DB.batch(TABLE_STATEMENTS.map((statement) => env.DB.prepare(statement)));
  const additions: Record<string, Record<string, string>> = { reimbursement_imports: { tolerance_bps: "INTEGER NOT NULL DEFAULT 500" }, reimbursement_sales: { duplicate_key: "TEXT NOT NULL DEFAULT ''", base_source: "TEXT NOT NULL DEFAULT 'NET_PRICE_VIGENTE'", base_status: "TEXT NOT NULL DEFAULT ''", reason_code: "TEXT NOT NULL DEFAULT ''", historical_margin_bps: "INTEGER", margin_variation_bps: "INTEGER", justification: "TEXT NOT NULL DEFAULT ''", justification_status: "TEXT NOT NULL DEFAULT ''", workflow_route: "TEXT NOT NULL DEFAULT 'exception'", workflow_status: "TEXT NOT NULL DEFAULT 'awaiting_global'", auto_check_json: "TEXT NOT NULL DEFAULT '{}'", global_decision_by_email: "TEXT NOT NULL DEFAULT ''", global_decision_at: "TEXT", dealer_consent_by_email: "TEXT NOT NULL DEFAULT ''", dealer_consent_at: "TEXT", settled_by_email: "TEXT NOT NULL DEFAULT ''", settled_at: "TEXT", settlement_document_number: "TEXT NOT NULL DEFAULT ''" }, reimbursement_approvals: { line_id: "INTEGER" } };
  for (const [table, columns] of Object.entries(additions)) { const info = await env.DB.prepare(`PRAGMA table_info(${table})`).all<{ name: string }>(); const existing = new Set((info.results ?? []).map((column) => column.name)); for (const [column, definition] of Object.entries(columns)) if (!existing.has(column)) await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`).run(); }
  await env.DB.prepare("CREATE INDEX IF NOT EXISTS reimbursement_sales_duplicate_key_idx ON reimbursement_sales(duplicate_key)").run();
  await env.DB.prepare("CREATE INDEX IF NOT EXISTS reimbursement_sales_workflow_status_idx ON reimbursement_sales(workflow_status)").run();
  return getDb();
}
